name: Build and Deploy to Lightsail

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: |
        set -e
        npm run build
    
    - name: Check build log
      run: cat .next/build-manifest.json || echo "Build manifest not found"

    - name: Check dist folder exists
      run: ls -la out

    - name: Deploy to Lightsail
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_KEY }}
        port: 22
        debug: true  # Enable verbose output
        timeout: 30s
        source: "."
        target: "/var/www/html/eyeblobs/app"
        strip_components: 1  
